language: python

python:
  - "3.6"

cache:
  directories:
    - /home/travis/build/louiscklaw/ubuntu_respin/origin

install:
  - sudo apt update && sudo apt install -y git wget genisoimage bc squashfs-tools xorriso
  - pip3 install pipenv
  - pipenv install fabric3

script:
  - fab helloworld
