# language: python

# python:
#   - "3.6"

# cache:
#   directories:
#     - /home/travis/build/louiscklaw/ubuntu_respin/origin

# install:
#   - sudo apt update && sudo apt install -y git wget genisoimage bc squashfs-tools xorriso
#   - pip3 install pipenv
#   - pipenv install pip==18 fabric3 pychalk

# script:
#   - pipenv run fab helloworld

# https://docs.travis-ci.com/user/docker/

dist: bionic

services:
  - docker

before_install:
  - docker --version
  - bash ./docker-build-image.sh

script:
  - bash ./build_all.sh
