language: python

python:
  - "3.6"

install:
  - sudo apt update && sudo apt install -y git wget genisoimage bc squashfs-tools xorriso
  - pip3 install pipenv
  - pipenv install fabric3

script:
  - wget http://releases.ubuntu.com/19.04/ubuntu-19.04-desktop-amd64.iso -O ./origin
  - fab helloworld
