name: send-slack-message

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build docker image
      run: bash ./docker-build-image.sh

    - name: build docker image
      run: bash ./_utils/build_all.sh

    - name: Send message to Slack API
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: build_result
        slack-text: |
          ${{ github.repository }} build done
          https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks

    - name: Result from "Send Message"
      run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
